FROM oven/bun:1-alpine

WORKDIR /app

RUN apk --no-cache add curl git

ARG NODE_AUTH_TOKEN
COPY .npmrc ./
COPY package.json bun.lock ./
RUN bun install

COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"]
